#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS5BEAMY5s396UJVSZQfIrGPbkLwxpERwrCz"
APP_SECRET: "VLSZ5kHLA6I+9wZ8wYedXmSZmn/tDEgiyLYkHW9D4cgcqzv40FqioPFY7U2hjOy4bkk/RKg0cyd6l+NjHa75pfBgj7qWPZr40oUDTc24PsyJw9lyIrDqa82PLM/5LVNbDW7Q9oZ24R2B0yybVHU9jylGX1te4FWuNSmnI/5JlFrVBtX96uw="

#계좌번호 앞 8자리
CANO: "73535499"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

LAST_GET_DATE : "20230611"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1089869359595388948/Tq4wvEQs5htzEzmVkdLNR2upENYjDlMzJO8h9JfpSF4K1EZ6g1t15As8JunCf0Pgd-Rc"